# Generated by Django 6.1 on 2026-09-27 02:52

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0003_remove_usuario_insurer_remove_usuario_policy_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LigaMensual',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mes', models.DateField(unique=True)),
                ('total_participantes', models.PositiveIntegerField(blank=True, null=True)),
                ('cerrada_en', models.DateField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LigaAmigos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField()),
                ('mes', models.DateField()),
                ('codigo_invitacion', models.CharField()),
                ('creador_usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.usuario')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TramoPremio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('orden', models.PositiveIntegerField(unique=True)),
                ('percentil_hasta', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('premio_descripcion', models.CharField()),
                ('monedas', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('percentil_hasta__gte', 0), ('percentil_hasta__lte', 100)), name='ck_tramo_percentil_hasta_0_100')],
            },
        ),
        migrations.CreateModel(
            name='MiembroLigaAmigos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pasos_acumulados_mes', models.PositiveIntegerField()),
                ('fecha_union', models.DateField()),
                ('liga_amigos', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='liga.ligaamigos')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.usuario')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('usuario', 'liga_amigos'), name='uq_usuario_liga_amigos')],
            },
        ),
        migrations.CreateModel(
            name='DesgloseLigaMensual',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pasos_acumulados_mes', models.PositiveIntegerField()),
                ('posicion_final', models.PositiveIntegerField(blank=True, null=True)),
                ('percentil', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.usuario')),
                ('liga_mensual', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='liga.ligamensual')),
                ('tramo_premio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='liga.tramopremio')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('usuario', 'liga_mensual'), name='uq_usuario_liga_mensual'), models.CheckConstraint(condition=models.Q(('percentil__isnull', True), models.Q(('percentil__gte', 0), ('percentil__lte', 100)), _connector='OR'), name='ck_desglose_percentil_0_100')],
            },
        ),
    ]
