# Generated by Django 6.1 on 2026-09-30 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liga', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ligaamigos',
            name='codigo_invitacion',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='ligaamigos',
            name='nombre',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='tramopremio',
            name='premio_descripcion',
            field=models.CharField(max_length=255),
        ),
    ]
