# Generated by Django 6.1 on 2026-10-04 05:30

import django.core.validators
from django.db import migrations, models

# Provisionales (3 oct 2026) hasta que Diego defina los montos. Se editan en el admin.
PODIO = ((1, 30), (2, 20), (3, 10))


def cargar_podio(apps, schema_editor):
    Premio = apps.get_model("liga", "PremioPodioLiga")
    for puesto, monedas in PODIO:
        Premio.objects.get_or_create(puesto=puesto, defaults={"monedas": monedas})


class Migration(migrations.Migration):

    dependencies = [
        ('liga', '0002_alter_ligaamigos_codigo_invitacion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PremioPodioLiga',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('puesto', models.PositiveSmallIntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)])),
                ('monedas', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ['puesto'],
            },
        ),
        migrations.AddField(
            model_name='desgloseligamensual',
            name='monedas',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='desgloseligamensual',
            name='workouts_acumulados_mes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='desgloseligamensual',
            name='puntos_mes',
            field=models.IntegerField(default=0),
        ),
        migrations.RunPython(cargar_podio, migrations.RunPython.noop),
    ]
