# Generated by Django 6.1 on 2026-09-23 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poincs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledger',
            name='puntos_intensidad',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ledger',
            name='puntos_pasos',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ledger',
            name='tope_diario_aplicado',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
