# Generated by Django 6.1 on 2026-09-26 05:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poincs', '0002_ledger_puntos_intensidad_ledger_puntos_pasos_and_more'),
        ('users', '0003_remove_usuario_insurer_remove_usuario_policy_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledger',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True, default='2026-09-25 23:38:21'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ledger',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ledger',
            name='tipo',
            field=models.CharField(choices=[('pasos', 'Pasos'), ('intensidad', 'Intensidad'), ('chequeo_medico', 'Chequeo médico'), ('ajuste_manual', 'Ajuste manual')], max_length=50),
        ),
        migrations.AlterField(
            model_name='ledger',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.usuario'),
        ),
        migrations.AddConstraint(
            model_name='ledger',
            constraint=models.UniqueConstraint(fields=('usuario', 'fecha', 'tipo', 'version_regla'), name='uq_ledger_usuario_fecha_tipo_version'),
        ),
    ]
