# Generated by Django 6.1 on 2026-09-26 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poincs', '0003_ledger_creado_en_alter_ledger_id_alter_ledger_tipo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='versionregla',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
