# Generated by Django 6.1 on 2026-10-01 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poincs', '0004_alter_versionregla_id'),
        ('users', '0003_remove_usuario_insurer_remove_usuario_policy_number_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='ledger',
            name='uq_ledger_usuario_fecha_tipo_version',
        ),
        migrations.AddConstraint(
            model_name='ledger',
            constraint=models.UniqueConstraint(condition=models.Q(('tipo', 'ajuste_manual'), _negated=True), fields=('usuario', 'fecha', 'tipo', 'version_regla'), name='uq_ledger_usuario_fecha_tipo_version'),
        ),
    ]
