# Generated by Django 6.1 on 2026-10-01 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poincs', '0005_remove_ledger_uq_ledger_usuario_fecha_tipo_version_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledger',
            name='tipo',
            field=models.CharField(choices=[('pasos', 'Pasos'), ('intensidad', 'Intensidad'), ('chequeo_medico', 'Chequeo médico'), ('ajuste_manual', 'Ajuste manual'), ('retroactivo_denegado', 'Retroactivo denegado')], max_length=50),
        ),
    ]
