# Generated by Django 6.1 on 2026-10-05 04:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_usuario_insurer_remove_usuario_policy_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntentoFallido',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=20)),
                ('clave', models.CharField(max_length=64)),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'indexes': [models.Index(fields=['tipo', 'clave', 'creado_en'], name='users_inten_tipo_d77c83_idx')],
            },
        ),
    ]
