# Generated by Django 6.1 on 2026-10-04 20:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_usuario_insurer_remove_usuario_policy_number_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IdentidadExterna',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('proveedor', models.CharField(choices=[('google', 'Google'), ('apple', 'Apple')], max_length=10)),
                ('sub', models.CharField(max_length=255)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='identidades_externas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('proveedor', 'sub'), name='uq_identidad_proveedor_sub'), models.UniqueConstraint(fields=('user', 'proveedor'), name='uq_identidad_user_proveedor')],
            },
        ),
    ]
