# Generated by Django 6.1 on 2026-10-06 14:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_correo_unico_sin_mayusculas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consentimiento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('version', models.CharField(max_length=20)),
                ('aceptado_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('revocado_en', models.DateTimeField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.usuario')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('revocado_en__isnull', True)), fields=('usuario', 'version'), name='uq_consentimiento_sin_revocar_por_version')],
            },
        ),
    ]
