# Generated by Django 6.1 on 2026-10-06 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_consentimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='dado_de_baja_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
