# Generated by Django 6.1 on 2026-08-25 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Muestra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=255)),
                ('inicio', models.DateTimeField()),
                ('fin', models.DateTimeField()),
                ('cantidad', models.PositiveIntegerField()),
                ('fuente_bundle', models.CharField(max_length=255)),
                ('fuente_nombre', models.CharField(max_length=255)),
                ('fuente_version', models.CharField(blank=True, max_length=255, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.usuario')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('usuario', 'external_id'), name='unique_muestra_usuario_external_id')],
            },
        ),
        migrations.CreateModel(
            name='Sesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=255)),
                ('inicio', models.DateTimeField()),
                ('fin', models.DateTimeField()),
                ('duracion_min', models.PositiveIntegerField()),
                ('tipo_actividad', models.CharField(max_length=255)),
                ('fc_promedio', models.PositiveIntegerField()),
                ('fc_maxima', models.PositiveIntegerField()),
                ('fuente_bundle', models.CharField(max_length=255)),
                ('fuente_nombre', models.CharField(max_length=255)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.usuario')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('usuario', 'external_id'), name='unique_sesion_usuario_external_id')],
            },
        ),
    ]
