# Generated by Django 6.1 on 2026-09-11 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MuestraBPM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=255)),
                ('inicio', models.DateTimeField()),
                ('fin', models.DateTimeField()),
                ('bpm', models.IntegerField()),
                ('fuente_bundle', models.CharField(max_length=255)),
                ('fuente_nombre', models.CharField(max_length=255)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.usuario')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('usuario', 'external_id'), name='unique_muestra_bpm_external_id')],
            },
        ),
    ]
