# Generated by Django 6.1 on 2026-09-15 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_alter_muestra_usuario_alter_sesion_usuario_and_more'),
        ('activities', '0002_muestrabpm'),
    ]

    operations = [
    ]
