# Generated by Django 6.1 on 2026-09-26 05:38

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_merge_20260915_1100'),
        ('users', '0003_remove_usuario_insurer_remove_usuario_policy_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumenDiario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('pasos_totales_dia', models.IntegerField()),
                ('workouts_cantidad', models.IntegerField(blank=True, null=True)),
                ('workouts_duracion_total_min', models.IntegerField(blank=True, null=True)),
                ('workouts_fc_promedio', models.IntegerField(blank=True, null=True)),
                ('workouts_fc_maxima', models.IntegerField(blank=True, null=True)),
                ('puntos_dia', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='muestra',
            name='dispositivo_fabricante',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='muestra',
            name='dispositivo_modelo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='muestra',
            name='dispositivo_nombre',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='muestrabpm',
            name='dispositivo_fabricante',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='muestrabpm',
            name='dispositivo_modelo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='muestrabpm',
            name='dispositivo_nombre',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='muestrabpm',
            name='fuente_version',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sesion',
            name='dispositivo_fabricante',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sesion',
            name='dispositivo_modelo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sesion',
            name='dispositivo_nombre',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sesion',
            name='fuente_version',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='muestra',
            name='cantidad',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(30000)]),
        ),
        migrations.AlterField(
            model_name='muestra',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='muestrabpm',
            name='bpm',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(230)]),
        ),
        migrations.AlterField(
            model_name='muestrabpm',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sesion',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sesion',
            name='tipo_actividad',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddConstraint(
            model_name='muestra',
            constraint=models.CheckConstraint(condition=models.Q(('cantidad__lte', 30000)), name='ck_muestra_cantidad_max_30000'),
        ),
        migrations.AddConstraint(
            model_name='muestrabpm',
            constraint=models.CheckConstraint(condition=models.Q(('bpm__gte', 30), ('bpm__lte', 230)), name='ck_muestra_cantidad_max_230'),
        ),
        migrations.AddField(
            model_name='resumendiario',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.usuario'),
        ),
        migrations.AddConstraint(
            model_name='resumendiario',
            constraint=models.UniqueConstraint(fields=('usuario', 'fecha'), name='uq_resumen_diario_usuario_fecha'),
        ),
    ]
