# Generated by Django 6.1 on 2026-09-26 05:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0004_resumendiario_muestra_dispositivo_fabricante_and_more'),
        ('users', '0003_remove_usuario_insurer_remove_usuario_policy_number_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='muestra',
            name='ck_muestra_cantidad_max_3000',
        ),
        migrations.AlterField(
            model_name='muestra',
            name='cantidad',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(30000)]),
        ),
        migrations.AddConstraint(
            model_name='muestra',
            constraint=models.CheckConstraint(condition=models.Q(('cantidad__lte', 3000)), name='ck_muestra_cantidad_max_30000'),
        ),
    ]
