# Generated by Django 6.1 on 2026-10-05 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0005_remove_muestra_ck_muestra_cantidad_max_3000_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumendiario',
            name='minutos_intenso',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resumendiario',
            name='minutos_ligero',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resumendiario',
            name='minutos_moderado',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
