"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

from datetime import timedelta
from pathlib import Path
import os

from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-2_4(5q7qn*e@6ie6aquxhe9)$ngb7i!(=t^cj_!d-!o6)zkg$#'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["localhost", "127.0.0.1", "172.20.10.3"]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Ya no autentica (ver REST_KNOX); queda instalada para sus migraciones y para
    # el formulario del login.
    'rest_framework.authtoken',
    'knox',

    "rest_framework",
    "corsheaders",
    "Apps.coins",
    "Apps.policies",
    "Apps.rewards",
    "Apps.activities",
    "Apps.poincs",
    'Apps.users.apps.UsersConfig',
    'Apps.liga',
    'Apps.objetivos',
]

REST_FRAMEWORK = {
    # Un token por inicio de sesión, guardado como hash, que vence (ver REST_KNOX). Es el
    # de Knox con dos casos de 500 convertidos en 401 (Apps/users/autenticacion.py).
    "DEFAULT_AUTHENTICATION_CLASSES": ["Apps.users.autenticacion.TokenDeSesion"],
    "DEFAULT_PERMISSION_CLASSES": ["rest_framework.permissions.IsAuthenticated"],
}

MIDDLEWARE = [
    # Tiene que ir antes de CommonMiddleware para poder contestar el
    # preflight OPTIONS que manda el navegador.
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# Deja que la app de Flutter corriendo en Chrome (flutter run -d chrome)
# llame a la API. Solo localhost, en cualquier puerto: Flutter web elige
# uno distinto cada vez. La app de iOS no pasa por CORS.
CORS_ALLOWED_ORIGIN_REGEXES = [
    r"^http://(localhost|127\.0\.0\.1)(:\d+)?$",
]

# Límites de intentos (registro, login y vincular póliza). Los de por defecto viven
# en services/intentos.py; esto los cambia sin tocar código, por ejemplo para
# probar en local donde todas las peticiones llegan con la misma IP:
#   LIMITES_DE_INTENTOS=login_ip=300/60,registro_ip=300/3600   (máximo/segundos)
def _limites_de_entorno():
    limites = {}
    for parte in (p.strip() for p in os.environ.get("LIMITES_DE_INTENTOS", "").split(",")):
        if not parte:
            continue
        try:
            tipo, valor = parte.split("=")
            maximo, segundos = valor.split("/")
            limites[tipo.strip()] = (int(maximo), int(segundos))
        except ValueError:
            raise ImproperlyConfigured(
                f"LIMITES_DE_INTENTOS: no entiendo {parte!r}. Formato: tipo=máximo/segundos"
            )
    return limites


LIMITES_DE_INTENTOS = _limites_de_entorno()

# Días SIN uso después de los cuales el token vence; cada uso lo renueva.
def _dias_de_vida_del_token():
    crudo = os.environ.get("DIAS_DE_VIDA_DEL_TOKEN", "30").strip()
    try:
        dias = int(crudo)
    except ValueError:
        dias = 0
    if dias < 1:
        raise ImproperlyConfigured(
            f"DIAS_DE_VIDA_DEL_TOKEN tiene que ser un número entero de días, 1 o más (llegó {crudo!r})."
        )
    return dias


DIAS_DE_VIDA_DEL_TOKEN = _dias_de_vida_del_token()


def _bool_de_entorno(nombre, defecto=False):
    crudo = os.environ.get(nombre, "").strip().casefold()
    if crudo == "":
        return defecto
    if crudo in ("1", "true", "si", "sí", "yes", "on"):
        return True
    if crudo in ("0", "false", "no", "off"):
        return False
    raise ImproperlyConfigured(f"{nombre} tiene que ser sí o no (llegó {crudo!r}).")


# Si es True, `POST /sync` rechaza (403 consentimiento_requerido) a quien no tiene el
# consentimiento vigente. Va APAGADO hasta que Swift deje ese día en la cola en vez de
# descartarlo (hoy trata cualquier 4xx como rechazo permanente) y Flutter tenga la pantalla.
CONSENTIMIENTO_OBLIGATORIO = _bool_de_entorno("CONSENTIMIENTO_OBLIGATORIO")

# Aunque se use a diario, a los 90 días de iniciar sesión hay que volver a entrar:
# un token robado no sirve para siempre. Si DIAS_DE_VIDA_DEL_TOKEN es mayor, manda este.
DIAS_MAXIMOS_DE_SESION = 90

# Tokens de django-rest-knox (decidido el 4 oct 2026, ver services/sesiones.py).
# El encabezado sigue siendo `Authorization: Token <clave>`.
REST_KNOX = {
    "TOKEN_TTL": timedelta(days=DIAS_DE_VIDA_DEL_TOKEN),
    # Cada uso corre el vencimiento, sin pasar del tope.
    "AUTO_REFRESH": True,
    "AUTO_REFRESH_MAX_TTL": timedelta(days=DIAS_MAXIMOS_DE_SESION),
    # El vencimiento se escribe en la base a lo más una vez por hora (decidido el 5 oct
    # 2026, como lo tenía Luis antes de A35): sobre 30 días, una hora no se nota y la
    # base se escribe mucho menos.
    "MIN_REFRESH_INTERVAL": 3600,
    # Sin TOKEN_LIMIT_PER_USER: con el límite lleno, Knox rechaza el login (403) y la
    # persona queda afuera. Las sesiones de más se borran al entrar (sesiones.py).
}

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

if os.environ.get("DB_ENGINE") == "postgresql":
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": os.environ.get("DB_NAME"),
            "USER": os.environ.get("DB_USER"),
            "PASSWORD": os.environ.get("DB_PASSWORD"),
            "HOST": os.environ.get("DB_HOST", "db"),
            "PORT": os.environ.get("DB_PORT", "5432"),
        }
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }

# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'DEBUG' if DEBUG else 'WARNING',
    },
}


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

# Hora de Guatemala: es la que decide cuándo empieza y termina un día (vigencia
# de una póliza, fecha de nacimiento futura, cierres semanales y mensuales).
# Las fechas con hora se siguen guardando en UTC en la base de datos.
TIME_ZONE = 'America/Guatemala'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}
