# Generated by Django 6.1 on 2026-09-26 05:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('poincs', '0003_ledger_creado_en_alter_ledger_id_alter_ledger_tipo_and_more'),
        ('users', '0003_remove_usuario_insurer_remove_usuario_policy_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Premio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField()),
                ('costo_monedas', models.PositiveIntegerField()),
                ('comercio_aliado', models.CharField(max_length=150)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MonedaLedger',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('tipo', models.CharField(choices=[('objetivo_cumplido', 'Objetivo cumplido'), ('liga_mensual', 'Liga mensual'), ('canje', 'Canje'), ('expiracion', 'Expiracion'), ('ajuste_manual', 'Ajuste manual')], max_length=50)),
                ('fecha', models.DateField()),
                ('fecha_expiracion', models.DateField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.usuario')),
                ('version_regla', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='poincs.versionregla')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Canje',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('costo_monedas', models.PositiveIntegerField()),
                ('fecha_canje', models.DateTimeField()),
                ('fecha_expiracion_cupon', models.DateField()),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('usado', 'Usado'), ('expirado', 'Expirado')], max_length=50)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.usuario')),
                ('premio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='coins.premio')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
