# Generated by Django 6.1 on 2026-10-04 04:58

import secrets

from django.db import migrations, models

# Mismo formato que services/premios.py (copiado: una migración no debe
# depender del código de la app, que puede cambiar).
_ALFABETO = "ABCDEFGHJKMNPQRSTUVWXYZ23456789"


def _codigo():
    parte = lambda: "".join(secrets.choice(_ALFABETO) for _ in range(4))  # noqa: E731
    return f"MV-{parte()}-{parte()}"


def codigos_para_los_canjes_viejos(apps, schema_editor):
    """Los canjes de antes de esta migración no tenían código: se les asigna uno."""
    Canje = apps.get_model("coins", "Canje")
    usados = set(Canje.objects.exclude(codigo=None).values_list("codigo", flat=True))
    for canje in Canje.objects.filter(codigo=None):
        codigo = _codigo()
        while codigo in usados:
            codigo = _codigo()
        usados.add(codigo)
        canje.codigo = codigo
        canje.save(update_fields=["codigo"])


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='canje',
            name='codigo',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='canje',
            name='ganado_en',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='canje',
            name='origen',
            field=models.CharField(choices=[('tienda', 'Tienda'), ('semana', 'Semana'), ('liga', 'La Liga')], default='tienda', max_length=10),
        ),
        migrations.AddField(
            model_name='canje',
            name='usado_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='premio',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='premio',
            name='categoria',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='premio',
            name='condiciones',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='premio',
            name='detalle',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='premio',
            name='fondo',
            field=models.CharField(blank=True, default='', max_length=7),
        ),
        migrations.AddField(
            model_name='premio',
            name='foto',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='premio',
            name='vigente_hasta',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='premio',
            name='zona',
            field=models.CharField(default='Guatemala', max_length=100),
        ),
        migrations.RunPython(codigos_para_los_canjes_viejos, migrations.RunPython.noop),
    ]
