# Generated by Django 6.1 on 2026-10-04 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0002_premios_y_cupones'),
        ('users', '0003_remove_usuario_insurer_remove_usuario_policy_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='canje',
            name='beneficio',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.CreateModel(
            name='Patrocinio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('semana', 'Semana'), ('liga', 'La Liga'), ('destacado', 'Premio destacado')], max_length=10)),
                ('desde', models.DateField()),
                ('hasta', models.DateField()),
                ('cupon', models.CharField(blank=True, default='', max_length=150)),
                ('acento', models.CharField(blank=True, default='', max_length=7)),
                ('fotos', models.JSONField(blank=True, default=list)),
                ('activo', models.BooleanField(default=True)),
                ('premio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='patrocinios', to='coins.premio')),
            ],
        ),
        migrations.AddField(
            model_name='canje',
            name='patrocinio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cupones', to='coins.patrocinio'),
        ),
        migrations.AddConstraint(
            model_name='canje',
            constraint=models.UniqueConstraint(condition=models.Q(('patrocinio__isnull', False)), fields=('usuario', 'patrocinio'), name='uq_canje_usuario_patrocinio'),
        ),
        migrations.AddConstraint(
            model_name='patrocinio',
            constraint=models.UniqueConstraint(condition=models.Q(('tipo__in', ['semana', 'liga'])), fields=('tipo', 'desde'), name='uq_patrocinio_tipo_desde'),
        ),
    ]
