# Generated by Django 6.1 on 2026-09-26 05:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0001_initial'),
        ('users', '0003_remove_usuario_insurer_remove_usuario_policy_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PolizaVinculada',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('policy_number', models.CharField(max_length=100)),
                ('insurer', models.CharField(max_length=100)),
                ('policy_start_date', models.DateField()),
                ('birth_date_confirmado', models.DateField(blank=True, null=True)),
                ('estado_verificación', models.CharField(choices=[('pendiente', 'pendiente'), ('verificada', 'verificada'), ('rechazada', 'rechazada')], max_length=10)),
                ('fecha_vinculación', models.DateField(auto_now_add=True)),
                ('fecha_verificación', models.DateField(blank=True, null=True)),
                ('usuario', models.OneToOneField(db_column='usuario_id', on_delete=django.db.models.deletion.PROTECT, to='users.usuario')),
            ],
        ),
        migrations.DeleteModel(
            name='Policy',
        ),
    ]
