# Generated by Django 6.1 on 2026-09-27 02:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0002_polizavinculada_delete_policy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='polizavinculada',
            old_name='birth_date_confirmado',
            new_name='birth_date_confirmada',
        ),
        migrations.RenameField(
            model_name='polizavinculada',
            old_name='estado_verificación',
            new_name='estado_verificacion',
        ),
        migrations.RemoveField(
            model_name='polizavinculada',
            name='fecha_verificación',
        ),
        migrations.RemoveField(
            model_name='polizavinculada',
            name='fecha_vinculación',
        ),
        migrations.AddField(
            model_name='polizavinculada',
            name='fecha_verificacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='polizavinculada',
            name='fecha_vinculacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
