# Generated by Django 6.1 on 2026-09-30 04:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    """Ajusta PolizaVinculada sin cambiar sus columnas ni sus datos.

    - estado_verificacion: pasa a TextChoices y queda "pendiente" por defecto.
    - usuario: agrega related_name="poliza" (se accede como usuario.poliza).

    Ninguno de los dos cambia columnas ni datos: son reglas de Django (valor
    por defecto y nombre de la relación inversa); Django no guarda el valor
    por defecto en la base. En SQLite igual reconstruye la tabla copiando
    todas las filas tal cual, porque SQLite no sabe alterar una columna en su
    lugar.
    """

    dependencies = [
        (
            "policies",
            "0003_rename_birth_date_confirmado_polizavinculada_birth_date_confirmada_and_more",
        ),
        ("users", "0003_remove_usuario_insurer_remove_usuario_policy_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="polizavinculada",
            name="estado_verificacion",
            field=models.CharField(
                choices=[
                    ("pendiente", "Pendiente"),
                    ("verificada", "Verificada"),
                    ("rechazada", "Rechazada"),
                ],
                default="pendiente",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="polizavinculada",
            name="usuario",
            field=models.OneToOneField(
                db_column="usuario_id",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="poliza",
                to="users.usuario",
            ),
        ),
    ]
