# Generated by Django 6.1 on 2026-09-30 19:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    """Agrega lo necesario para verificar pólizas contra la aseguradora.

    - PolizaVinculada.motivo_rechazo: por qué se rechazó (columna nueva, nula).
    - PolizaVinculada.policy_start_date: ahora admite nulo, porque una póliza
      rechazada o inexistente no tiene fecha de inicio confirmada.
    - RegistroAseguradora: tabla nueva y vacía con el documento simulado de la
      aseguradora (solo para pruebas).

    No rompe datos existentes: las filas de PolizaVinculada se conservan tal
    cual (una columna nueva nula y una restricción más laxa).
    """

    dependencies = [
        ("policies", "0004_poliza_estado_por_defecto"),
    ]

    operations = [
        migrations.AddField(
            model_name="polizavinculada",
            name="motivo_rechazo",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="polizavinculada",
            name="policy_start_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="RegistroAseguradora",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("numero_poliza", models.CharField(max_length=100, unique=True)),
                ("aseguradora", models.CharField(max_length=100)),
                ("nombre", models.CharField(max_length=100)),
                ("apellido", models.CharField(max_length=100)),
                ("fecha_nacimiento", models.DateField()),
                ("plan", models.CharField(max_length=100)),
                (
                    "prima_mensual_gtq",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("deducible_gtq", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "coaseguro_pct",
                    models.PositiveSmallIntegerField(
                        validators=[django.core.validators.MaxValueValidator(100)]
                    ),
                ),
                ("red", models.CharField(max_length=100)),
                ("vigencia_inicio", models.DateField()),
                ("vigencia_fin", models.DateField()),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("vigente", "Vigente"),
                            ("vencida", "Vencida"),
                            ("cancelada", "Cancelada"),
                            ("suspendida", "Suspendida"),
                        ],
                        max_length=10,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("vigencia_fin__gte", models.F("vigencia_inicio"))
                        ),
                        name="ck_registro_vigencia_fin_gte_inicio",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("coaseguro_pct__lte", 100)),
                        name="ck_registro_coaseguro_0_100",
                    ),
                ],
            },
        ),
    ]
