# Generated by Django 6.1 on 2026-09-27 02:52

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0003_remove_usuario_insurer_remove_usuario_policy_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaPorPasosObjetivo',
            fields=[
                ('objetivo_numero', models.PositiveIntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(13)])),
                ('meta_pasos', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ObjetivoSemanal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField(unique=True)),
                ('fecha_fin', models.DateField()),
                ('meta_pasos', models.PositiveIntegerField()),
                ('meta_workouts', models.PositiveBigIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('numero', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('anio', models.PositiveIntegerField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CumplimientoSemanal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pasos_semanales', models.PositiveIntegerField()),
                ('workouts_acumulados', models.PositiveIntegerField()),
                ('cumplido', models.BooleanField()),
                ('evaluado_en', models.DateField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.usuario')),
                ('objetivo_semanal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='objetivos.objetivosemanal')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('usuario', 'objetivo_semanal'), name='uq_cumplimiento_usuario_objetivo')],
            },
        ),
        migrations.CreateModel(
            name='ProgresoObjetivoUsuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('objetivo_actual', models.PositiveIntegerField(default=1)),
                ('objetivo_maximo_alcanzado', models.PositiveIntegerField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.usuario')),
                ('sesion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='objetivos.season')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('usuario', 'sesion'), name='uq_progreso_objetivo_usuario')],
            },
        ),
    ]
